name: Push Docker Image to GCR

on:
  push:
    branches:
      - '*'

jobs:
  push_to_gcr:
    name: Push Docker Image to GCR
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Authenticate Docker to GCR
      run: gcloud auth configure-docker

    - name: Build and push Docker image
      run: |
        # Build the Docker image
        docker build -t gcr.io/PROJECT-ID/IMAGE:TAG .
        
        # Push the Docker image to GCR
        docker push gcr.io/PROJECT-ID/IMAGE:TAG

    - name: Logout from Docker registry
      run: docker logout
